import fs from "node:fs";
import path from "node:path";
import type { DatabasePlan } from "../planner/DatabaseDesigner.js";

export interface MigrationGenerateResult {
  written: string[];
  errors: string[];
}

export class DatabaseMigrationGenerator {
  generate(plan: DatabasePlan, outputDir: string): MigrationGenerateResult {
    const written: string[] = [];
    const errors: string[] = [];

    const migrationsDir = path.join(outputDir, "prisma", "migrations");
    const timestamp = new Date().toISOString().replace(/[-T:.Z]/g, "").slice(0, 14);
    const migDir = path.join(migrationsDir, `${timestamp}_init`);

    try {
      fs.mkdirSync(migDir, { recursive: true });
    } catch (err) {
      errors.push(`migrations dir: ${err instanceof Error ? err.message : String(err)}`);
      return { written, errors };
    }

    // migration.sql
    const sqlLines: string[] = ["-- Migration: Initial schema", "-- Generated by SATSET", ""];
    for (const entity of plan.entities) {
      sqlLines.push(`-- Table: ${entity.name}`);
      sqlLines.push(`CREATE TABLE IF NOT EXISTS "${entity.name}" (`);
      const fieldLines = entity.fields.map((f) => {
        const type = this.toSqlType(f.type);
        const pk = f.primaryKey ? " PRIMARY KEY" : "";
        const notNull = f.required && !f.primaryKey ? " NOT NULL" : "";
        const unique = f.unique ? " UNIQUE" : "";
        const def = f.default ? ` DEFAULT ${f.default.replace(/['"]/g, "")}` : "";
        return `  "${f.name}" ${type}${pk}${notNull}${unique}${def}`;
      });
      sqlLines.push(fieldLines.join(",\n") + "\n);", "");
    }

    const sqlPath = path.join(migDir, "migration.sql");
    try {
      fs.writeFileSync(sqlPath, sqlLines.join("\n"), "utf8");
      written.push(sqlPath);
    } catch (err) {
      errors.push(`migration.sql: ${err instanceof Error ? err.message : String(err)}`);
    }

    // migration_lock.toml
    const lockPath = path.join(migrationsDir, "migration_lock.toml");
    try {
      fs.writeFileSync(lockPath, `# Please do not edit this file manually\nprovider = "postgresql"\n`, "utf8");
      written.push(lockPath);
    } catch { /* ignore */ }

    // seed.ts
    const seedTs = this.buildSeedTs(plan);
    const seedPath = path.join(outputDir, "prisma", "seed.ts");
    try {
      fs.writeFileSync(seedPath, seedTs, "utf8");
      written.push(seedPath);
    } catch (err) {
      errors.push(`seed.ts: ${err instanceof Error ? err.message : String(err)}`);
    }

    // seed-data.ts
    const seedDataTs = this.buildSeedDataTs(plan);
    const seedDataPath = path.join(outputDir, "prisma", "seed-data.ts");
    try {
      fs.writeFileSync(seedDataPath, seedDataTs, "utf8");
      written.push(seedDataPath);
    } catch (err) {
      errors.push(`seed-data.ts: ${err instanceof Error ? err.message : String(err)}`);
    }

    // Add db scripts to package.json
    const pkgPath = path.join(outputDir, "package.json");
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8")) as { scripts?: Record<string, string> };
        pkg.scripts = pkg.scripts ?? {};
        pkg.scripts["db:generate"] = "prisma generate";
        pkg.scripts["db:migrate"] = "prisma migrate dev";
        pkg.scripts["db:seed"] = "tsx prisma/seed.ts";
        pkg.scripts["db:reset"] = "prisma migrate reset --force";
        fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), "utf8");
        written.push(pkgPath);
      } catch (err) {
        errors.push(`package.json scripts: ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    return { written, errors };
  }

  private toSqlType(type: string): string {
    switch (type) {
      case "Int": return "INTEGER";
      case "Float": return "DOUBLE PRECISION";
      case "Boolean": return "BOOLEAN";
      case "DateTime": return "TIMESTAMP WITH TIME ZONE";
      case "Json": return "JSONB";
      default: return "TEXT";
    }
  }

  private buildSeedTs(plan: DatabasePlan): string {
    return `import { PrismaClient } from "@prisma/client";
import { seedData } from "./seed-data.js";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

${plan.entities.slice(0, 3).map((e) => `  for (const item of seedData.${e.name.toLowerCase()}s ?? []) {
    await prisma.${e.name.charAt(0).toLowerCase() + e.name.slice(1)}.upsert({
      where: { id: item.id },
      update: {},
      create: item,
    });
  }`).join("\n\n")}

  console.log("Seeding complete.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
`;
  }

  private buildSeedDataTs(plan: DatabasePlan): string {
    const entries = plan.entities.slice(0, 3).map((e) => {
      const nameField = e.fields.find((f) => f.name === "name");
      const emailField = e.fields.find((f) => f.name === "email");
      const sample = `{ id: "seed-${e.name.toLowerCase()}-1"${nameField ? `, name: "Sample ${e.name}"` : ""}${emailField ? `, email: "sample@example.com"` : ""} }`;
      return `  ${e.name.toLowerCase()}s: [${sample}]`;
    });

    return `export const seedData = {\n${entries.join(",\n")}\n};\n`;
  }
}
