import type { DomainModel, DomainEntity, EntityField } from "./DomainModelGenerator.js";

export interface DatabaseDesignResult {
  schema: string;
}

function prismaType(type: string): string {
  switch (type) {
    case "integer": return "Int";
    case "float": return "Float";
    case "boolean": return "Boolean";
    case "datetime": return "DateTime";
    default: return "String";
  }
}

function fieldLine(field: EntityField): string {
  const type = prismaType(field.type);
  const optional = field.required ? "" : "?";
  const attrs: string[] = [];

  if (field.primaryKey) {
    attrs.push("@id", "@default(cuid())");
  } else if (field.unique) {
    attrs.push("@unique");
  }

  if (field.name === "createdAt") attrs.push("@default(now())");
  if (field.name === "updatedAt") attrs.push("@updatedAt");

  const attrStr = attrs.length > 0 ? "  " + attrs.join(" ") : "";
  return `  ${field.name}  ${type}${optional}${attrStr}`;
}

function relationFields(entity: DomainEntity, allEntities: DomainEntity[]): string[] {
  const lines: string[] = [];

  for (const rel of entity.relations) {
    if (rel.type === "many-to-one") {
      const target = allEntities.find((e) => e.name === rel.to);
      if (!target) continue;
      const capTo = rel.to.charAt(0).toUpperCase() + rel.to.slice(1);
      const fkField = `${rel.to}Id`;
      // Add relation field if not already in fields
      const hasFk = entity.fields.some((f) => f.name === fkField);
      if (!hasFk) {
        lines.push(`  ${fkField}  String`);
      }
      lines.push(`  ${rel.to}  ${capTo}  @relation(fields: [${fkField}], references: [id])`);
    } else if (rel.type === "one-to-many") {
      const capTo = rel.to.charAt(0).toUpperCase() + rel.to.slice(1);
      lines.push(`  ${rel.to}s  ${capTo}[]`);
    } else if (rel.type === "many-to-many") {
      const capTo = rel.to.charAt(0).toUpperCase() + rel.to.slice(1);
      lines.push(`  ${rel.to}s  ${capTo}[]`);
    }
  }

  return lines;
}

function indexLines(entity: DomainEntity): string[] {
  const fkFields = entity.fields
    .filter((f) => f.name.endsWith("Id") && !f.primaryKey)
    .map((f) => f.name);

  const relFkFields = entity.relations
    .filter((r) => r.type === "many-to-one")
    .map((r) => `${r.to}Id`);

  const allFks = Array.from(new Set([...fkFields, ...relFkFields]));

  return allFks.map((fk) => `  @@index([${fk}])`);
}

function modelBlock(entity: DomainEntity, allEntities: DomainEntity[]): string {
  const cap = entity.name.charAt(0).toUpperCase() + entity.name.slice(1);
  const fieldLines = entity.fields.map(fieldLine);
  const relLines = relationFields(entity, allEntities);
  const idxLines = indexLines(entity);

  const all = [...fieldLines, ...relLines, ...idxLines];
  return `model ${cap} {\n${all.join("\n")}\n}`;
}

const HEADER = `// Generated by SATSET DatabaseDesigner

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

export class DatabaseDesigner {
  design(model: DomainModel): DatabaseDesignResult {
    const blocks = model.entities.map((e) => modelBlock(e, model.entities));
    const schema = HEADER + blocks.join("\n\n");
    return { schema };
  }
}
