import fs from "node:fs";
import path from "node:path";
import type { ExecutionPlan } from "../ai/ModulePlanner.js";

export interface PrismaSchemaGenerateResult {
  written: string[];
  errors: string[];
}

const MODEL_MAP: Record<string, string> = {
  user: `model User {\n  id        String   @id @default(cuid())\n  email     String   @unique\n  name      String?\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}`,
  auth: `model Session {\n  id        String   @id @default(cuid())\n  userId    String\n  token     String   @unique\n  expiresAt DateTime\n  createdAt DateTime @default(now())\n}`,
  product: `model Product {\n  id        String   @id @default(cuid())\n  name      String\n  price     Float\n  stock     Int      @default(0)\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}`,
  category: `model Category {\n  id   String @id @default(cuid())\n  name String @unique\n}`,
  order: `model Order {\n  id        String   @id @default(cuid())\n  total     Float\n  status    String   @default("pending")\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}`,
  payment: `model Payment {\n  id        String   @id @default(cuid())\n  amount    Float\n  method    String\n  status    String   @default("pending")\n  createdAt DateTime @default(now())\n}`,
  inventory: `model Inventory {\n  id        String   @id @default(cuid())\n  productId String\n  quantity  Int\n  updatedAt DateTime @updatedAt\n}`,
  cart: `model Cart {\n  id        String   @id @default(cuid())\n  userId    String\n  createdAt DateTime @default(now())\n}`,
};

const HEADER = `// This is your Prisma schema file
// Generated by SATSET

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

export class PrismaSchemaGenerator {
  generate(plan: ExecutionPlan, outputDir: string): PrismaSchemaGenerateResult {
    const written: string[] = [];
    const errors: string[] = [];

    const models = plan.modules
      .filter((m) => MODEL_MAP[m.name])
      .map((m) => MODEL_MAP[m.name]!)
      .join("\n\n");

    const schema = HEADER + (models || "// No models generated");

    try {
      const prismaDir = path.join(outputDir, "prisma");
      fs.mkdirSync(prismaDir, { recursive: true });
      const target = path.join(prismaDir, "schema.prisma");
      fs.writeFileSync(target, schema, "utf8");
      written.push(target);
    } catch (err) {
      errors.push(`failed to write schema.prisma: ${err instanceof Error ? err.message : String(err)}`);
    }

    return { written, errors };
  }
}
