CREATE TABLE IF NOT EXISTS ticketing (
  id TEXT PRIMARY KEY,
  id TEXT NOT NULL,
  kode TEXT NOT NULL,
  nama TEXT NOT NULL,
  status TEXT NOT NULL,
  keterangan TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
