apiVersion: apps/v1
kind: Deployment
metadata:
  name: VillageSystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VillageSystem
  template:
    metadata:
      labels:
        app: VillageSystem
    spec:
      containers:
        - name: VillageSystem
          image: VillageSystem:latest
          ports:
            - containerPort: 3000
