# Host Application

Generated by existing SATSET generator plugin pipeline.

- Workspace: {{names.module.title}}
- Apps: admin, api, worker
- Packages: shared
- Runtime: docker, env, prisma

This document is generated automatically.