apiVersion: apps/v1
kind: Deployment
metadata:
  name: HRIS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HRIS
  template:
    metadata:
      labels:
        app: HRIS
    spec:
      containers:
        - name: HRIS
          image: HRIS:latest
          ports:
            - containerPort: 3000
