apiVersion: apps/v1
kind: Deployment
metadata:
  name: POS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: POS
  template:
    metadata:
      labels:
        app: POS
    spec:
      containers:
        - name: POS
          image: POS:latest
          ports:
            - containerPort: 3000
