export default function Page(
){
    const {
        canView,
        canCreate,
        canUpdate,
        canDelete
    } = usePermission();
  return (
    <div>
      <h1 style={{fontSize:28,fontWeight:"bold"}}>
        outbound Module
      </h1>

      <p>Generated by SATSET CLI</p>
    </div>
  )
}
