import { SatsetPresetTarget } from "../sdk/contracts.js";

export const SATSET_PRESET_TARGETS: readonly SatsetPresetTarget[] = [
  "crm",
  "inventory",
  "purchasing",
  "wisata",
  "hotel",
  "restoran",
  "parkir",
  "laporan",
  "analytics",
  "dashboard",
  "erp",
  "pos",
  "finance",
  "hr",
  "warehouse",
  "reservation",
  "ticket",
  "visitor",
  "destination",
  "reporting",
  "notification",
  "workflow",
  "master-data",
  "cafe",
  "restaurant",
  "souvenir",
  "membership",
  "loyalty",
  "employee",
  "supplier",
  "vendor",
  "customer"
];