apiVersion: apps/v1
kind: Deployment
metadata:
  name: ERP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ERP
  template:
    metadata:
      labels:
        app: ERP
    spec:
      containers:
        - name: ERP
          image: ERP:latest
          ports:
            - containerPort: 3000
