export enum Capability {
  Node = "Node",
  TypeScript = "TypeScript",
  JavaScript = "JavaScript",
  React = "React",
  NextJS = "NextJS",
  Prisma = "Prisma",
  TailwindCSS = "TailwindCSS",
  PNPM = "PNPM",
  NPM = "NPM",
  Yarn = "Yarn",
  Bun = "Bun",
  SQLite = "SQLite",
  PostgreSQL = "PostgreSQL",
  MySQL = "MySQL",
  MongoDB = "MongoDB",
  Docker = "Docker",
  TurboRepo = "TurboRepo",
  Workspace = "Workspace",
  Git = "Git",
  VSCode = "VSCode"
}
