import type { MobileDashboardProfile, MobileNavItem, MobileQuickActionData, MobileStatCardData, MobileTaskItem, MobileNotificationItem } from "./mobileDashboardTypes.js";

const stat = (data: MobileStatCardData): MobileStatCardData => data;
const action = (data: MobileQuickActionData): MobileQuickActionData => data;
const task = (data: MobileTaskItem): MobileTaskItem => data;
const notif = (data: MobileNotificationItem): MobileNotificationItem => data;
const nav = (data: MobileNavItem): MobileNavItem => data;

const baseNotifications: MobileNotificationItem[] = [
  notif({ title: "Sinkronisasi selesai", detail: "Data dashboard terbaru sudah masuk", time: "Baru saja", tone: "success" }),
  notif({ title: "Pengingat shift", detail: "Periksa status tugas sebelum jam sibuk", time: "10 menit lalu", tone: "warn" }),
  notif({ title: "Pusat notifikasi aktif", detail: "Notifikasi penting akan tampil di sini", time: "Hari ini", tone: "info" }),
];

const baseQuickActions: MobileQuickActionData[] = [
  action({ label: "Buka Command", description: "Cari modul atau aksi cepat", action: "openCmd()", icon: "command", tone: "brand" }),
  action({ label: "Muat Ulang", description: "Segarkan dashboard", action: "rld()", icon: "dashboard", tone: "info" }),
  action({ label: "Tema", description: "Pindah tema aplikasi", action: "tDark()", icon: "health", tone: "success" }),
  action({ label: "Notifikasi", description: "Lihat pesan terbaru", action: "toggleNotif(event)", icon: "bell", tone: "warn" }),
];

function createProfile(profile: MobileDashboardProfile): MobileDashboardProfile {
  return profile;
}

export const mobileDashboardProfiles: Record<MobileDashboardProfile["role"], MobileDashboardProfile> = {
  "super-admin": createProfile({
    role: "super-admin",
    badge: "Super Admin",
    title: "Dashboard Android Enterprise",
    greeting: "Selamat datang, Administrator",
    shiftLabel: "Shift Command Center",
    shiftHint: "Pantau seluruh operasi dari satu layar",
    summary: "Ringkasan enterprise, KPI utama, dan aksi cepat prioritas untuk kontrol penuh harian.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Ticket Hari Ini", source: "ticketToday", value: "-", hint: "Penjualan tiket aktif", tone: "brand", action: "gt('list','ticketing')", icon: "summary" }),
      stat({ id: "mobile-stat-2", label: "Booking Hari Ini", source: "bookingToday", value: "-", hint: "Reservasi masuk", tone: "info", action: "gt('list','reservasi')", icon: "timeline" }),
      stat({ id: "mobile-stat-3", label: "Pendapatan Cafe", source: "cafeRevenue", value: "-", hint: "Shift cafe berjalan", tone: "success", action: "gt('list','cafe')", icon: "chart" }),
      stat({ id: "mobile-stat-4", label: "Laba Hari Ini", source: "financeProfit", value: "-", hint: "Kontrol margin", tone: "warn", action: "gt('list','finance')", icon: "health" }),
    ],
    shortcuts: [
      action({ label: "Ticketing", description: "Buka penjualan tiket", action: "gt('list','ticketing')", icon: "summary", tone: "brand" }),
      action({ label: "Reservasi", description: "Kelola booking", action: "gt('list','reservasi')", icon: "timeline", tone: "info" }),
      action({ label: "Finance", description: "Pantau kas dan bank", action: "gt('list','finance')", icon: "chart", tone: "success" }),
      action({ label: "Accounting", description: "Masuk ke jurnal", action: "gt('list','accounting')", icon: "command", tone: "warn" }),
    ],
    tasks: [
      task({ title: "Review KPI", detail: "Cek indikator harian sebelum jam ramai", badge: "Prioritas", action: "gt('dashboard')", tone: "brand" }),
      task({ title: "Validasi Booking", detail: "Verifikasi antrean reservasi pagi ini", badge: "Hari ini", action: "gt('list','reservasi')", tone: "info" }),
      task({ title: "Kontrol Kas", detail: "Periksa saldo dan mutasi teratas", badge: "Finance", action: "gt('list','finance')", tone: "success" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Ticket", action: "gt('list','ticketing')", icon: "summary", route: "ticketing" }),
      nav({ label: "Booking", action: "gt('list','reservasi')", icon: "timeline", route: "reservasi" }),
      nav({ label: "Finance", action: "gt('list','finance')", icon: "chart", route: "finance" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  owner: createProfile({
    role: "owner",
    badge: "Owner",
    title: "Dashboard Android Owner",
    greeting: "Selamat pagi, Owner",
    shiftLabel: "Shift Pengawasan",
    shiftHint: "Fokus pada kas, margin, dan arah bisnis",
    summary: "Visibilitas ringkas untuk owner dengan fokus pendapatan, kas, dan evaluasi performa.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Saldo Kas", source: "financeCash", value: "-", hint: "Likuiditas utama", tone: "success", action: "gt('list','finance')", icon: "summary" }),
      stat({ id: "mobile-stat-2", label: "Saldo Bank", source: "financeBank", value: "-", hint: "Akun bank aktif", tone: "info", action: "gt('list','finance')", icon: "chart" }),
      stat({ id: "mobile-stat-3", label: "Laba Hari Ini", source: "financeProfit", value: "-", hint: "Margin operasional", tone: "brand", action: "gt('list','accounting')", icon: "health" }),
      stat({ id: "mobile-stat-4", label: "Ticket Hari Ini", source: "ticketToday", value: "-", hint: "Traffic masuk", tone: "warn", action: "gt('list','ticketing')", icon: "summary" }),
    ],
    shortcuts: [
      action({ label: "Finance", description: "Lihat kas dan bank", action: "gt('list','finance')", icon: "chart", tone: "success" }),
      action({ label: "Accounting", description: "Cek laba rugi", action: "gt('list','accounting')", icon: "command", tone: "brand" }),
      action({ label: "Outbound", description: "Pantau sesi dan peserta", action: "gt('list','outbound')", icon: "timeline", tone: "info" }),
      action({ label: "Cafe", description: "Pantau pendapatan cafe", action: "gt('list','cafe')", icon: "summary", tone: "warn" }),
    ],
    tasks: [
      task({ title: "Review keuangan", detail: "Bandingkan cash flow dengan target", badge: "Owner", action: "gt('list','finance')", tone: "success" }),
      task({ title: "Pantau booking", detail: "Cek performa reservasi dan occupancy", badge: "Hari ini", action: "gt('list','reservasi')", tone: "info" }),
      task({ title: "Audit performa", detail: "Buka ringkasan modul bisnis utama", badge: "Audit", action: "gt('dashboard')", tone: "warn" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Finance", action: "gt('list','finance')", icon: "chart", route: "finance" }),
      nav({ label: "Accounting", action: "gt('list','accounting')", icon: "command", route: "accounting" }),
      nav({ label: "Laporan", action: "gt('list','jurnal')", icon: "summary", route: "jurnal" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  manager: createProfile({
    role: "manager",
    badge: "Manager",
    title: "Dashboard Android Manager",
    greeting: "Selamat bekerja, Manager",
    shiftLabel: "Shift Operasional",
    shiftHint: "Koordinasi booking, outbound, dan cafe",
    summary: "Pantau kesiapan tim, antrean kerja, dan pekerjaan lapangan dari satu dashboard.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Booking Hari Ini", source: "bookingToday", value: "-", hint: "Antrian reservasi", tone: "brand", action: "gt('list','reservasi')", icon: "timeline" }),
      stat({ id: "mobile-stat-2", label: "Outbound", source: "outboundSessions", value: "-", hint: "Sesi berjalan", tone: "info", action: "gt('list','outbound')", icon: "chart" }),
      stat({ id: "mobile-stat-3", label: "Attendance", source: "outboundAttendance", value: "-", hint: "Kehadiran peserta", tone: "success", action: "gt('list','outbound')", icon: "health" }),
      stat({ id: "mobile-stat-4", label: "Task Hari Ini", source: "taskCount", value: "-", hint: "Pekerjaan prioritas", tone: "warn", action: "openCmd()", icon: "command" }),
    ],
    shortcuts: [
      action({ label: "Booking", description: "Kelola antrian", action: "gt('list','reservasi')", icon: "timeline", tone: "brand" }),
      action({ label: "Outbound", description: "Pantau sesi lapangan", action: "gt('list','outbound')", icon: "chart", tone: "info" }),
      action({ label: "Cafe", description: "Lihat operasi cafe", action: "gt('list','cafe')", icon: "summary", tone: "success" }),
      action({ label: "Command", description: "Cari aksi tim", action: "openCmd()", icon: "command", tone: "warn" }),
    ],
    tasks: [
      task({ title: "Cek booking", detail: "Pastikan slot hari ini terisi", badge: "Manager", action: "gt('list','reservasi')", tone: "brand" }),
      task({ title: "Koordinasi outbound", detail: "Review kesiapan peserta dan alat", badge: "Operasional", action: "gt('list','outbound')", tone: "info" }),
      task({ title: "Validasi cafe", detail: "Pastikan shift dan order berjalan", badge: "Cafe", action: "gt('list','cafe')", tone: "success" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Booking", action: "gt('list','reservasi')", icon: "timeline", route: "reservasi" }),
      nav({ label: "Outbound", action: "gt('list','outbound')", icon: "chart", route: "outbound" }),
      nav({ label: "Cafe", action: "gt('list','cafe')", icon: "summary", route: "cafe" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  "kasir-cafe": createProfile({
    role: "kasir-cafe",
    badge: "Kasir Cafe",
    title: "Dashboard Android Kasir Cafe",
    greeting: "Selamat datang di POS Cafe",
    shiftLabel: "Shift Barista",
    shiftHint: "Pantau order, pembayaran, dan kitchen",
    summary: "Fokus ke kecepatan order, pembayaran, dan kesiapan dapur pada layar Android.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Order Hari Ini", source: "cafeOrders", value: "-", hint: "Transaksi aktif", tone: "brand", action: "gt('list','cafe')", icon: "summary" }),
      stat({ id: "mobile-stat-2", label: "Pendapatan Cafe", source: "cafeRevenue", value: "-", hint: "Revenue shift", tone: "success", action: "gt('list','cafe')", icon: "chart" }),
      stat({ id: "mobile-stat-3", label: "Queue Kitchen", source: "queue", value: "-", hint: "Antrian masak", tone: "warn", action: "openCafeKitchenDisplay()", icon: "timeline" }),
      stat({ id: "mobile-stat-4", label: "Kas Aktif", source: "financeCash", value: "-", hint: "Cash ready", tone: "info", action: "openCafeShift()", icon: "health" }),
    ],
    shortcuts: [
      action({ label: "POS Cafe", description: "Buka kasir cafe", action: "openCafePos()", icon: "summary", tone: "brand" }),
      action({ label: "Order Baru", description: "Input order cepat", action: "quickCafeOrder()", icon: "action", tone: "info" }),
      action({ label: "Kitchen", description: "Pantau dapur", action: "openCafeKitchenDisplay()", icon: "timeline", tone: "success" }),
      action({ label: "Cetak Struk", description: "Print transaksi terakhir", action: "printLatestCafeReceipt()", icon: "chevronRight", tone: "warn" }),
    ],
    tasks: [
      task({ title: "Ambil order", detail: "Lanjutkan input order masuk", badge: "POS", action: "openCafePos()", tone: "brand" }),
      task({ title: "Review kitchen", detail: "Cek antrian masakan terbuka", badge: "Kitchen", action: "openCafeKitchenDisplay()", tone: "warn" }),
      task({ title: "Tutup shift", detail: "Amankan kas sebelum pergantian", badge: "Shift", action: "closeCafeShift()", tone: "success" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Cafe", action: "gt('list','cafe')", icon: "summary", route: "cafe" }),
      nav({ label: "Ticket", action: "gt('list','ticketing')", icon: "timeline", route: "ticketing" }),
      nav({ label: "Finance", action: "gt('list','finance')", icon: "chart", route: "finance" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  loket: createProfile({
    role: "loket",
    badge: "Loket",
    title: "Dashboard Android Loket",
    greeting: "Selamat bekerja di loket",
    shiftLabel: "Shift Front Desk",
    shiftHint: "Fokus pada tiket, booking, dan antrean",
    summary: "Pusatkan pekerjaan loket pada tiket, reservasi, dan verifikasi antrean di Android.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Tiket Terjual", source: "ticketSales", value: "-", hint: "Penjualan aktif", tone: "brand", action: "gt('list','ticketing')", icon: "summary" }),
      stat({ id: "mobile-stat-2", label: "Scan Valid", source: "ticketScan", value: "-", hint: "Validasi masuk", tone: "success", action: "gt('list','ticketing')", icon: "health" }),
      stat({ id: "mobile-stat-3", label: "Booking Hari Ini", source: "bookingToday", value: "-", hint: "Reservasi loket", tone: "info", action: "gt('list','reservasi')", icon: "timeline" }),
      stat({ id: "mobile-stat-4", label: "Antrean", source: "queue", value: "-", hint: "Status menunggu", tone: "warn", action: "gt('list','reservasi')", icon: "command" }),
    ],
    shortcuts: [
      action({ label: "Ticketing", description: "Jual dan scan tiket", action: "gt('list','ticketing')", icon: "summary", tone: "brand" }),
      action({ label: "Booking", description: "Buka reservasi", action: "gt('list','reservasi')", icon: "timeline", tone: "info" }),
      action({ label: "Check In", description: "Verifikasi kedatangan", action: "gt('list','ticketing')", icon: "health", tone: "success" }),
      action({ label: "Finance", description: "Lihat pembayaran", action: "gt('list','finance')", icon: "chart", tone: "warn" }),
    ],
    tasks: [
      task({ title: "Cetak tiket", detail: "Layani tiket masuk hari ini", badge: "Loket", action: "gt('list','ticketing')", tone: "brand" }),
      task({ title: "Konfirmasi booking", detail: "Verifikasi antrean reservasi", badge: "Front Desk", action: "gt('list','reservasi')", tone: "info" }),
      task({ title: "Pantau antrean", detail: "Jaga flow loket tetap lancar", badge: "Queue", action: "openCmd()", tone: "warn" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Ticket", action: "gt('list','ticketing')", icon: "summary", route: "ticketing" }),
      nav({ label: "Booking", action: "gt('list','reservasi')", icon: "timeline", route: "reservasi" }),
      nav({ label: "Finance", action: "gt('list','finance')", icon: "chart", route: "finance" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  booking: createProfile({
    role: "booking",
    badge: "Booking",
    title: "Dashboard Android Booking",
    greeting: "Selamat bekerja di booking desk",
    shiftLabel: "Shift Reservasi",
    shiftHint: "Kelola slot, konfirmasi, dan waiting list",
    summary: "Khusus untuk tim booking dengan fokus pada occupancy, waiting list, dan approval.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Booking Hari Ini", source: "bookingToday", value: "-", hint: "Reservasi aktif", tone: "brand", action: "gt('list','reservasi')", icon: "timeline" }),
      stat({ id: "mobile-stat-2", label: "Occupancy", source: "bookingOccupancy", value: "-", hint: "Kapasitas terpakai", tone: "success", action: "gt('list','reservasi')", icon: "chart" }),
      stat({ id: "mobile-stat-3", label: "Waiting List", source: "queue", value: "-", hint: "Antrean menunggu", tone: "warn", action: "gt('list','reservasi')", icon: "command" }),
      stat({ id: "mobile-stat-4", label: "Konfirmasi", source: "bookingToday", value: "-", hint: "Approval hari ini", tone: "info", action: "gt('list','reservasi')", icon: "health" }),
    ],
    shortcuts: [
      action({ label: "Booking Baru", description: "Input reservasi baru", action: "gt('form','reservasi')", icon: "timeline", tone: "brand" }),
      action({ label: "Waiting List", description: "Filter antrean", action: "gt('list','reservasi')", icon: "command", tone: "warn" }),
      action({ label: "Occupancy", description: "Lihat okupansi", action: "gt('dashboard')", icon: "chart", tone: "success" }),
      action({ label: "Ticketing", description: "Kaitkan booking dengan tiket", action: "gt('list','ticketing')", icon: "summary", tone: "info" }),
    ],
    tasks: [
      task({ title: "Konfirmasi booking", detail: "Tinjau antrean yang menunggu approval", badge: "Booking", action: "gt('list','reservasi')", tone: "brand" }),
      task({ title: "Update occupancy", detail: "Perbarui kapasitas harian", badge: "Desk", action: "gt('dashboard')", tone: "info" }),
      task({ title: "Follow up pelanggan", detail: "Hubungi booking yang belum lengkap", badge: "Follow-up", action: "openCmd()", tone: "warn" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Booking", action: "gt('list','reservasi')", icon: "timeline", route: "reservasi" }),
      nav({ label: "Ticket", action: "gt('list','ticketing')", icon: "summary", route: "ticketing" }),
      nav({ label: "Laporan", action: "gt('list','jurnal')", icon: "chart", route: "jurnal" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  ticketing: createProfile({
    role: "ticketing",
    badge: "Ticketing",
    title: "Dashboard Android Ticketing",
    greeting: "Selamat bekerja di ticketing desk",
    shiftLabel: "Shift Gate",
    shiftHint: "Jual tiket, scan, dan validasi masuk",
    summary: "Pusat kerja tiket untuk penjualan, scan, dan validasi gate di Android.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Tiket Terjual", source: "ticketSales", value: "-", hint: "Penjualan loket", tone: "brand", action: "gt('list','ticketing')", icon: "summary" }),
      stat({ id: "mobile-stat-2", label: "Scan Valid", source: "ticketScan", value: "-", hint: "Validasi gate", tone: "success", action: "gt('list','ticketing')", icon: "health" }),
      stat({ id: "mobile-stat-3", label: "Refund", source: "ticketRefund", value: "-", hint: "Transaksi refund", tone: "warn", action: "gt('list','ticketing')", icon: "chart" }),
      stat({ id: "mobile-stat-4", label: "Queue Gate", source: "queue", value: "-", hint: "Antrean aktif", tone: "info", action: "openTicketScanner()", icon: "command" }),
    ],
    shortcuts: [
      action({ label: "Quick Sale", description: "Jual tiket cepat", action: "quickTicketSale()", icon: "summary", tone: "brand" }),
      action({ label: "Scan", description: "Buka scanner", action: "openTicketScanner()", icon: "health", tone: "success" }),
      action({ label: "Refund", description: "Lihat refund", action: "exportTicketReport('refund')", icon: "chart", tone: "warn" }),
      action({ label: "Penggunaan", description: "Laporan penggunaan", action: "exportTicketReport('penggunaan')", icon: "timeline", tone: "info" }),
    ],
    tasks: [
      task({ title: "Scan gate", detail: "Validasi tiket masuk pengunjung", badge: "Gate", action: "openTicketScanner()", tone: "brand" }),
      task({ title: "Jual tiket", detail: "Lanjutkan penjualan loket", badge: "POS", action: "quickTicketSale()", tone: "success" }),
      task({ title: "Rekap laporan", detail: "Siapkan laporan penjualan harian", badge: "Laporan", action: "exportTicketReport('penjualan')", tone: "warn" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Ticket", action: "gt('list','ticketing')", icon: "summary", route: "ticketing" }),
      nav({ label: "Booking", action: "gt('list','reservasi')", icon: "timeline", route: "reservasi" }),
      nav({ label: "Laporan", action: "gt('list','jurnal')", icon: "chart", route: "jurnal" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  finance: createProfile({
    role: "finance",
    badge: "Finance",
    title: "Dashboard Android Finance",
    greeting: "Selamat bekerja di finance desk",
    shiftLabel: "Shift Finance",
    shiftHint: "Pantau kas, bank, dan cash flow",
    summary: "Ringkasan keuangan mobile untuk saldo kas, bank, dan kontrol profit harian.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Saldo Kas", source: "financeCash", value: "-", hint: "Likuiditas tunai", tone: "success", action: "gt('list','finance')", icon: "summary" }),
      stat({ id: "mobile-stat-2", label: "Saldo Bank", source: "financeBank", value: "-", hint: "Saldo rekening", tone: "info", action: "gt('list','finance')", icon: "chart" }),
      stat({ id: "mobile-stat-3", label: "Pendapatan", source: "financeRevenue", value: "-", hint: "Masuk hari ini", tone: "brand", action: "gt('list','finance')", icon: "health" }),
      stat({ id: "mobile-stat-4", label: "Cash Flow", source: "financeFlow", value: "-", hint: "Aliran kas", tone: "warn", action: "gt('list','finance')", icon: "command" }),
    ],
    shortcuts: [
      action({ label: "Kas Masuk", description: "Tambah penerimaan", action: "openFinanceCashIn()", icon: "summary", tone: "success" }),
      action({ label: "Kas Keluar", description: "Catat pengeluaran", action: "openFinanceCashOut()", icon: "chart", tone: "warn" }),
      action({ label: "Rekonsiliasi", description: "Sinkron rekening", action: "openFinanceReconcile()", icon: "health", tone: "info" }),
      action({ label: "Laporan", description: "Buka report finance", action: "openFinanceReport()", icon: "command", tone: "brand" }),
    ],
    tasks: [
      task({ title: "Input transaksi", detail: "Rekap mutasi kas masuk/keluar", badge: "Finance", action: "gt('list','finance')", tone: "success" }),
      task({ title: "Rekonsiliasi bank", detail: "Cocokkan saldo rekening", badge: "Bank", action: "openFinanceReconcile()", tone: "info" }),
      task({ title: "Laporkan profit", detail: "Tutup hari dengan ringkasan laba", badge: "P/L", action: "gt('list','accounting')", tone: "warn" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Finance", action: "gt('list','finance')", icon: "chart", route: "finance" }),
      nav({ label: "Accounting", action: "gt('list','accounting')", icon: "command", route: "accounting" }),
      nav({ label: "Laporan", action: "gt('list','jurnal')", icon: "summary", route: "jurnal" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  accounting: createProfile({
    role: "accounting",
    badge: "Accounting",
    title: "Dashboard Android Accounting",
    greeting: "Selamat bekerja di accounting desk",
    shiftLabel: "Shift Akuntansi",
    shiftHint: "Jurnal, neraca, dan closing buku",
    summary: "Dashboard mobile akuntansi untuk jurnal, trial balance, dan closing status.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Jumlah Jurnal", source: "journalCount", value: "-", hint: "Posting hari ini", tone: "brand", action: "gt('list','accounting')", icon: "command" }),
      stat({ id: "mobile-stat-2", label: "Trial Balance", source: "trialBalance", value: "-", hint: "Keseimbangan akun", tone: "success", action: "openAccountingTrialBalance()", icon: "health" }),
      stat({ id: "mobile-stat-3", label: "Neraca", source: "neracaStatus", value: "-", hint: "Validasi neraca", tone: "info", action: "openAccountingBalanceSheet()", icon: "summary" }),
      stat({ id: "mobile-stat-4", label: "Closing", source: "closingStatus", value: "-", hint: "Status penutupan", tone: "warn", action: "closeAccountingBook()", icon: "chart" }),
    ],
    shortcuts: [
      action({ label: "Input Jurnal", description: "Posting transaksi", action: "openAccountingJournalInput()", icon: "command", tone: "brand" }),
      action({ label: "Ledger", description: "Buka buku besar", action: "openAccountingLedger()", icon: "summary", tone: "info" }),
      action({ label: "Trial Balance", description: "Cek keseimbangan", action: "openAccountingTrialBalance()", icon: "health", tone: "success" }),
      action({ label: "Closing", description: "Tutup buku", action: "closeAccountingBook()", icon: "chart", tone: "warn" }),
    ],
    tasks: [
      task({ title: "Posting jurnal", detail: "Masukkan jurnal terbaru ke sistem", badge: "Journal", action: "openAccountingJournalInput()", tone: "brand" }),
      task({ title: "Validasi trial balance", detail: "Pastikan sisi debit kredit seimbang", badge: "Review", action: "openAccountingTrialBalance()", tone: "success" }),
      task({ title: "Closing status", detail: "Cek apakah periode sudah tertutup", badge: "Closing", action: "closeAccountingBook()", tone: "warn" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Accounting", action: "gt('list','accounting')", icon: "command", route: "accounting" }),
      nav({ label: "Finance", action: "gt('list','finance')", icon: "chart", route: "finance" }),
      nav({ label: "Laporan", action: "gt('list','jurnal')", icon: "summary", route: "jurnal" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  instruktur: createProfile({
    role: "instruktur",
    badge: "Instruktur",
    title: "Dashboard Android Instruktur",
    greeting: "Selamat bekerja di area outbound",
    shiftLabel: "Shift Lapangan",
    shiftHint: "Kelola sesi, peserta, dan alat",
    summary: "Fokus pada peserta, jadwal, dan kesiapan peralatan lapangan untuk instruktur.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Sesi Hari Ini", source: "outboundSessions", value: "-", hint: "Jadwal aktif", tone: "brand", action: "gt('list','outbound')", icon: "timeline" }),
      stat({ id: "mobile-stat-2", label: "Peserta", source: "outboundParticipants", value: "-", hint: "Peserta terdaftar", tone: "info", action: "gt('list','outbound')", icon: "summary" }),
      stat({ id: "mobile-stat-3", label: "Attendance", source: "outboundAttendance", value: "-", hint: "Kehadiran", tone: "success", action: "gt('list','outbound')", icon: "health" }),
      stat({ id: "mobile-stat-4", label: "Peralatan", source: "equipmentReady", value: "-", hint: "Peralatan siap", tone: "warn", action: "gt('list','outbound')", icon: "chart" }),
    ],
    shortcuts: [
      action({ label: "Jadwal", description: "Buka jadwal sesi", action: "openOutboundSchedule()", icon: "timeline", tone: "brand" }),
      action({ label: "Absensi", description: "Catat kehadiran", action: "markOutboundAttendanceQuick()", icon: "health", tone: "success" }),
      action({ label: "Instruktur", description: "Lihat distribusi", action: "openOutboundInstructor()", icon: "summary", tone: "info" }),
      action({ label: "Peralatan", description: "Cek inventory alat", action: "openOutboundEquipment()", icon: "chart", tone: "warn" }),
    ],
    tasks: [
      task({ title: "Briefing sesi", detail: "Siapkan sesi outbound hari ini", badge: "Lapangan", action: "openOutboundSchedule()", tone: "brand" }),
      task({ title: "Absensi peserta", detail: "Verifikasi kehadiran peserta", badge: "Check In", action: "openOutboundCheckIn()", tone: "success" }),
      task({ title: "Peralatan", detail: "Pastikan alat aman dipakai", badge: "Equipment", action: "openOutboundEquipment()", tone: "warn" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Outbound", action: "gt('list','outbound')", icon: "chart", route: "outbound" }),
      nav({ label: "Ticket", action: "gt('list','ticketing')", icon: "summary", route: "ticketing" }),
      nav({ label: "Booking", action: "gt('list','reservasi')", icon: "timeline", route: "reservasi" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
  maintenance: createProfile({
    role: "maintenance",
    badge: "Maintenance",
    title: "Dashboard Android Maintenance",
    greeting: "Selamat bekerja di maintenance desk",
    shiftLabel: "Shift Maintenance",
    shiftHint: "Kontrol kendaraan dan peralatan",
    summary: "Pantau kesiapan kendaraan, peralatan, dan antrean maintenance dari Android.",
    statCards: [
      stat({ id: "mobile-stat-1", label: "Kendaraan", source: "vehicleCount", value: "-", hint: "Armada aktif", tone: "brand", action: "gt('list','kendaraan')", icon: "summary" }),
      stat({ id: "mobile-stat-2", label: "Peralatan", source: "equipmentCount", value: "-", hint: "Item siap pakai", tone: "info", action: "gt('list','outbound')", icon: "chart" }),
      stat({ id: "mobile-stat-3", label: "Maintenance", source: "maintenanceQueue", value: "-", hint: "Antrean servis", tone: "warn", action: "gt('list','kendaraan')", icon: "timeline" }),
      stat({ id: "mobile-stat-4", label: "Readiness", source: "readiness", value: "-", hint: "Kesiapan operasi", tone: "success", action: "gt('dashboard')", icon: "health" }),
    ],
    shortcuts: [
      action({ label: "Kendaraan", description: "Buka data armada", action: "gt('list','kendaraan')", icon: "summary", tone: "brand" }),
      action({ label: "Peralatan", description: "Cek alat outbound", action: "openOutboundEquipment()", icon: "chart", tone: "info" }),
      action({ label: "Instruktur", description: "Koordinasi sesi", action: "openOutboundInstructor()", icon: "timeline", tone: "success" }),
      action({ label: "Laporan", description: "Pantau pekerjaan", action: "openOutboundReport()", icon: "command", tone: "warn" }),
    ],
    tasks: [
      task({ title: "Servis kendaraan", detail: "Prioritaskan armada yang siap jalan", badge: "Maintenance", action: "gt('list','kendaraan')", tone: "brand" }),
      task({ title: "Cek peralatan", detail: "Pastikan alat outbound aman", badge: "Equipment", action: "openOutboundEquipment()", tone: "info" }),
      task({ title: "Koordinasi lapangan", detail: "Update status ke tim outbound", badge: "Sync", action: "openCmd()", tone: "warn" }),
    ],
    notifications: baseNotifications,
    quickActions: baseQuickActions,
    navItems: [
      nav({ label: "Beranda", action: "gt('dashboard')", icon: "dashboard", route: "dashboard" }),
      nav({ label: "Kendaraan", action: "gt('list','kendaraan')", icon: "summary", route: "kendaraan" }),
      nav({ label: "Outbound", action: "gt('list','outbound')", icon: "chart", route: "outbound" }),
      nav({ label: "Laporan", action: "gt('list','jurnal')", icon: "summary", route: "jurnal" }),
      nav({ label: "More", action: "openCmd()", icon: "chevronRight" }),
    ],
  }),
};